name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./punk-chat
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: punk-chat/package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: npm ci

      # ----- BEGIN MORE DIAGNOSTIC STEPS -----
      - name: List structure of punk-chat
        run: |
          echo "Listing punk-chat root:"
          ls -la .
          echo "Listing punk-chat/lib:"
          ls -la ./lib || echo "punk-chat/lib directory not found"
          echo "Listing punk-chat/app:"
          ls -la ./app || echo "punk-chat/app directory not found"
          echo "Listing punk-chat/components:"
          ls -la ./components || echo "punk-chat/components directory not found"
        # This step already defaults to working-directory: ./punk-chat

      - name: Show relevant imports from app/page.tsx
        run: |
          echo "--- Relevant imports from ./app/page.tsx ---"
          grep -E "@/(lib|components)/" ./app/page.tsx || echo "No matching imports found in app/page.tsx or file not found"
          echo "--------------------------------------------"
        # This step already defaults to working-directory: ./punk-chat

      - name: Show tsconfig.json content (from inside punk-chat)
        run: |
          echo "--- Contents of ./tsconfig.json (from within punk-chat) ---"
          cat ./tsconfig.json
          echo "-----------------------------------------------------------"
        # This step already defaults to working-directory: ./punk-chat
      # ----- END MORE DIAGNOSTIC STEPS -----

      - name: Build with Next.js
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./punk-chat/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
